name: remote_file_manager
description: Flutter app to browse/upload/download files from laptop over LAN
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.2
  file_picker: ^10.3.7
  path_provider: ^2.0.15
  permission_handler: ^12.0.1
  shared_preferences: ^2.1.1
